/**
 * Zenkipay API
 * Definition of technical specification of the product; Zenkipay is a gateway cryptocurrency payment system that allows merchant\'s to receive payments on their e-commerce portals. Unlike other platforms, Zenkipay ensures customer satisfaction through its payment process. guarantee deposit (delivered product and expected quality) to settle payment to the merchant, thus avoiding the loss of client assets due to online scams.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zenki.fi
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Summary of the amount paid in crypto currency by the buyer.
*/
export class CryptoPayment {
    /**
    * Payment amount in cryptocurrency.
    */
    'amount': string;
    /**
    * Code of the cryptocurrency supported by Zenkipay, see: https://developer.zenki.fi/global-v1/docs/zenkipay-recursos-catalogos-criptomonedas-soportadas
    */
    'currency': string;
    /**
    * Supported blockchains list.  Posibles valroes: * Bitcoin * Ethereum * Litecoin * Bitcoin Cash * Solana * Algorand * Polygon * Arbitrum * BSC * Avalanche * Ripple * Terra * Cardano * Polkadot * Tron * Stellar * Ethereum Classic * Hedera Hashgraph * Tezos * EOSIO * Fantom Opera * ZCash * Celo * Dash * XDC Network
    */
    'blockchain': string;
    /**
    * Unique identifier of the transaction, provided by the blockchain.
    */
    'transactionHash'?: string | null;
    /**
    * URL to check the status of the transaction directly on the blockchain.
    */
    'networkScanUrl'?: string | null;
    /**
    * Payment status transaction in the blockchain network.  Possible values: * CONFIRMING                        - Pending confirmation on the blockchain. * PARTIALLY_COMPLETED               - One or more of of the transaction records have completed successfully (Only for Aggregated transactions). * COMPLETED                         - Successfully completed. * CANCELLED                         - The transaction was rejected by the Zenkipay Staff or by the 3rd party service. * REJECTED                          - La transacción fue rechazada por el servicio de terceros. * BLOCKED                           - The transaction was blocked due to a policy rule. * FAILED                            - The transaction has failed.
    */
    'transactionStatus'?: CryptoPayment.TransactionStatusEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "blockchain",
            "baseName": "blockchain",
            "type": "string"
        },
        {
            "name": "transactionHash",
            "baseName": "transactionHash",
            "type": "string"
        },
        {
            "name": "networkScanUrl",
            "baseName": "networkScanUrl",
            "type": "string"
        },
        {
            "name": "transactionStatus",
            "baseName": "transactionStatus",
            "type": "CryptoPayment.TransactionStatusEnum"
        }    ];

    static getAttributeTypeMap() {
        return CryptoPayment.attributeTypeMap;
    }
}

export namespace CryptoPayment {
    export enum TransactionStatusEnum {
        Confirming = <any> 'CONFIRMING',
        PartiallyCompleted = <any> 'PARTIALLY_COMPLETED',
        Completed = <any> 'COMPLETED',
        Cancelled = <any> 'CANCELLED',
        Rejected = <any> 'REJECTED',
        Blocked = <any> 'BLOCKED',
        Failed = <any> 'FAILED'
    }
}
