/**
 * Zenkipay API
 * Definition of technical specification of the product; Zenkipay is a gateway cryptocurrency payment system that allows merchant\'s to receive payments on their e-commerce portals. Unlike other platforms, Zenkipay ensures customer satisfaction through its payment process. guarantee deposit (delivered product and expected quality) to settle payment to the merchant, thus avoiding the loss of client assets due to online scams.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zenki.fi
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* General information of the merchant.
*/
export class MerchantMerchantInfo {
    /**
    * Commercial name of the merchant that you registered when you created your Zenki account.
    */
    'commercialName': string;
    /**
    * Merchant legal name that you register during the Zenki account activation process.
    */
    'legalName'?: string;
    /**
    * Merchant account type.  Possible values: * PERSONAL - Natural person with commercial activity. * ENTITY - Company with commercial activity
    */
    'accountType': MerchantMerchantInfo.AccountTypeEnum;
    /**
    * State of the documentary process in which the merchant is located.  Possible values: * PENDING      - Indicates that you still need to send information or documents to complete your KYC process. * APPROVED     - The documentary registration process has been completed and the Zenki staff has authorized the business to operate. * REQUEST_INFO - Zenki Staff requested more information or change in trade documents. * REJECTED     - Zenki Staff definitively rejected the merchant request.
    */
    'kycStatus': MerchantMerchantInfo.KycStatusEnum;
    /**
    * Status of the integration process in merchant is located.  Possible values: * PENDING   - It indicates that the merchant has not yet concluded its technical integration process and is not yet in a productive environment. * COMPLETED - Indicates that the merchant has completed its technical integration process and is already in production or live.
    */
    'integrationStatus': MerchantMerchantInfo.IntegrationStatusEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "commercialName",
            "baseName": "commercialName",
            "type": "string"
        },
        {
            "name": "legalName",
            "baseName": "legalName",
            "type": "string"
        },
        {
            "name": "accountType",
            "baseName": "accountType",
            "type": "MerchantMerchantInfo.AccountTypeEnum"
        },
        {
            "name": "kycStatus",
            "baseName": "kycStatus",
            "type": "MerchantMerchantInfo.KycStatusEnum"
        },
        {
            "name": "integrationStatus",
            "baseName": "integrationStatus",
            "type": "MerchantMerchantInfo.IntegrationStatusEnum"
        }    ];

    static getAttributeTypeMap() {
        return MerchantMerchantInfo.attributeTypeMap;
    }
}

export namespace MerchantMerchantInfo {
    export enum AccountTypeEnum {
        Personal = <any> 'PERSONAL',
        Entity = <any> 'ENTITY'
    }
    export enum KycStatusEnum {
        Pending = <any> 'PENDING',
        Approved = <any> 'APPROVED',
        RequestInfo = <any> 'REQUEST_INFO',
        Rejected = <any> 'REJECTED'
    }
    export enum IntegrationStatusEnum {
        Pending = <any> 'PENDING',
        Completed = <any> 'COMPLETED'
    }
}
