/**
 * Zenkipay API
 * Definition of technical specification of the product; Zenkipay is a gateway cryptocurrency payment system that allows merchant\'s to receive payments on their e-commerce portals. Unlike other platforms, Zenkipay ensures customer satisfaction through its payment process. guarantee deposit (delivered product and expected quality) to settle payment to the merchant, thus avoiding the loss of client assets due to online scams.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zenki.fi
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Claim process detail, when a payment is made and Zenkipay cannot identify it and associate it with the payment order.
*/
export class OrderClaim {
    /**
    * Reason for filing the claim.
    */
    'reason'?: string | null;
    /**
    * Claim current status.      Possible values: * OPEN     - The claim process has started. * REFUND   - The claim process has been closed and a partial or full refund of the full amount of the order has been made. * RESOLVED - The claim process has been closed without making any reimbursement movement to the buyer, only the payment transaction is associated with the indicated order. * REJECTED - When the claim does not apply, because it tries to associate a payment that does not match the transaction data.
    */
    'status': OrderClaim.StatusEnum;
    /**
    * Date and time the clearing started, in milliseconds and UTC format.      The Unix epoch (or Unix time or POSIX time or Unix timestamp) is the number of seconds elapsed since January 1, 1970 (midnight UTC/GMT), not counting leap seconds (in ISO 8601: 1970-01-01T00: 00:00Z)
    */
    'createdAt': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "reason",
            "baseName": "reason",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "OrderClaim.StatusEnum"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return OrderClaim.attributeTypeMap;
    }
}

export namespace OrderClaim {
    export enum StatusEnum {
        Open = <any> 'OPEN',
        Refund = <any> 'REFUND',
        Resolved = <any> 'RESOLVED',
        Rejected = <any> 'REJECTED'
    }
}
