/**
 * Zenkipay API
 * Definition of technical specification of the product; Zenkipay is a gateway cryptocurrency payment system that allows merchant\'s to receive payments on their e-commerce portals. Unlike other platforms, Zenkipay ensures customer satisfaction through its payment process. guarantee deposit (delivered product and expected quality) to settle payment to the merchant, thus avoiding the loss of client assets due to online scams.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zenki.fi
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class RequestTokenOAuth2 {
    /**
    * Client ID Key must be obtained from the Zenkipay portal in the security section.
    */
    'clientId': string;
    /**
    * Client Secret Key in Zenkipay must be obtained from the Zenkipay portal in the security section.
    */
    'clientSecret': string;
    /**
    * Permission type, for all operations carried out in the Zenkipay API from the merchant\'s server, it is required to send the value \'client_credentials\' as grant type.
    */
    'grantType': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "clientId",
            "baseName": "clientId",
            "type": "string"
        },
        {
            "name": "clientSecret",
            "baseName": "clientSecret",
            "type": "string"
        },
        {
            "name": "grantType",
            "baseName": "grantType",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RequestTokenOAuth2.attributeTypeMap;
    }
}

