/**
 * Zenkipay API
 * Definition of technical specification of the product; Zenkipay is a gateway cryptocurrency payment system that allows merchant\'s to receive payments on their e-commerce portals. Unlike other platforms, Zenkipay ensures customer satisfaction through its payment process. guarantee deposit (delivered product and expected quality) to settle payment to the merchant, thus avoiding the loss of client assets due to online scams.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zenki.fi
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class TokenOAuth2 {
    /**
    * The access token that will be required to send in all requests to the Zenki API.
    */
    'accessToken': string;
    /**
    * The access token that will be required to send as a header in all requests to the Zenki API.
    */
    'tokenType': string;
    /**
    * Access token expiration time in seconds.
    */
    'expiresIn': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accessToken",
            "baseName": "accessToken",
            "type": "string"
        },
        {
            "name": "tokenType",
            "baseName": "tokenType",
            "type": "string"
        },
        {
            "name": "expiresIn",
            "baseName": "expiresIn",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return TokenOAuth2.attributeTypeMap;
    }
}

