/**
 * Zenkipay API
 * Definition of technical specification of the product; Zenkipay is a gateway cryptocurrency payment system that allows merchant\'s to receive payments on their e-commerce portals. Unlike other platforms, Zenkipay ensures customer satisfaction through its payment process. guarantee deposit (delivered product and expected quality) to settle payment to the merchant, thus avoiding the loss of client assets due to online scams.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zenki.fi
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Courier details used for the shipment.
*/
export class TrackingExternalCourier {
    /**
    * Unique messaging identifier provided by Zenkipay:  Example of some couriers:   * 190135  139Express  http://www.139express.com/   * 190524  1688        https://www.1688.com/   * 190659  17EXP       https://www.17-exp.com/   * 190349  1TONG       http://www.1tongexpress.com/  To know the complete list of couriers see: https://developer.zenki.fi/global-v1/docs/zenkipay-recursos-catalogos-mensajerias-soportadas
    */
    'key': string;
    /**
    * Unique country identifier, the definition of the ISO_3166-1 standard is used with 2 characters, see: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2 or https://www.iso.org/iso-3166-country-codes.html
    */
    'countryCodeIso2': string;
    /**
    * Courier website.  To know the complete list of couriers see: https://developer.zenki.fi/global-v1/docs/zenkipay-recursos-catalogos-mensajerias-soportadas
    */
    'url'?: string | null;
    /**
    * Courier name.  To know the complete list of couriers see: https://developer.zenki.fi/global-v1/docs/zenkipay-recursos-catalogos-mensajerias-soportadas
    */
    'name'?: string | null;
    /**
    * Courier name.  To know the complete list of couriers see: https://developer.zenki.fi/global-v1/docs/zenkipay-recursos-catalogos-mensajerias-soportadas
    */
    'nameZhCn'?: string | null;
    /**
    * Courier name.        To know the complete list of couriers see: https://developer.zenki.fi/global-v1/docs/zenkipay-recursos-catalogos-mensajerias-soportadas
    */
    'nameZhHk'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "key",
            "baseName": "key",
            "type": "string"
        },
        {
            "name": "countryCodeIso2",
            "baseName": "countryCodeIso2",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "nameZhCn",
            "baseName": "nameZhCn",
            "type": "string"
        },
        {
            "name": "nameZhHk",
            "baseName": "nameZhHk",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return TrackingExternalCourier.attributeTypeMap;
    }
}

